### ISSUE TITLE
No intellisense for graphql blocks in svelte files

### ISSUE THREAD

**Issue by maraisr** [0no-co/GraphQLSP#237] opened 2024-02-24 01:48 UTC
Im playing with tada in a svelte project of mine, and noticed only `ts` files has intellisense working. Than `<script lang="ts">` blocks as well, despite other typescript features working in there.

Here is a blank sveltekit project that illustrates this: https://codesandbox.io/p/devbox/magical-dream-kwdjm7

Points of interest:
- `src/routes/+page.svelte` demonstrates declaring a fragment in `context="module"` which is then imported by the page loader. Confirmed working through document composition, just no types in the svelte file.
- `src/routes/+page.ts` shows a working intellisense. The import name from a svelte file is red, but that's a import type quirk thingy. 

I'm not sure if the sandbox is setup correctly, but the same was experienced locally.

**Comment by JoviDeCroock** [comment] 2024-02-24 06:48
Duplicate of https://github.com/0no-co/GraphQLSP/issues/168

**Closed by JoviDeCroock** 2024-02-24 06:48 UTC
